//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrderingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<key_values> key_values { get; set; }
        public virtual DbSet<m_item_category> m_item_category { get; set; }
        public virtual DbSet<m_user> m_user { get; set; }
        public virtual DbSet<t_order> t_order { get; set; }
        public virtual DbSet<t_order_calendar> t_order_calendar { get; set; }
        public virtual DbSet<t_order_close> t_order_close { get; set; }
        public virtual DbSet<t_billing> t_billing { get; set; }
        public virtual DbSet<t_billing_close> t_billing_close { get; set; }
        public virtual DbSet<m_user_role> m_user_role { get; set; }
    }
}
