//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_values
    {
        public int id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
    }
}
