//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order_close
    {
        public int id { get; set; }
        public int order_calendar_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime closed_at { get; set; }
    
        public virtual t_order_calendar t_order_calendar { get; set; }
        public virtual m_user m_user { get; set; }
    }
}
